// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wixmnvdmcnlbiyxnfpfc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndpeG1udmRtY25sYml5eG5mcGZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzI3MzMsImV4cCI6MjA2MjM0ODczM30.aJ79XhRURXbtIkPBVFVgQKeviXeyjg7g05yrDSEwWdw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);